[project]
name = "mono-fmed"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas[excel]>=2.3.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.403",
    "ruff>=0.12.4",
]
